settings:
  import/resolver:
    typescript: {}
env:
  browser: true
  es2022: true
  vue/setup-compiler-macros: true
ignorePatterns:
  - '/src/api/'
  - '/node_modules/'
  - '**/node_modules/'
extends:
  - plugin:vue/vue3-recommended
  - '@vue/eslint-config-typescript/recommended'
  - '@vue/eslint-config-prettier'
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: './tsconfig.json'
plugins:
  - import
  - vue
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: error
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: _
  '@typescript-eslint/no-unused-expressions':
    - error
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
      allowHigherOrderFunctions: true
      allowDirectConstAssertionInArrowFunctions: true
      allowConciseArrowFunctionExpressionsStartingWithVoid: false
  max-len:
    - error
    - code: 150
      ignoreStrings: true
      ignorePattern: class="[^"]*"
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: true
  vue/max-attributes-per-line:
    - error
    - singleline: 1
      multiline:
        max: 1
        allowFirstLine: false
  'vue/multi-word-component-names': 'off'
