export const DATE_FORMAT_YEAR_MONTH_DAY = 'yyyy-MM-dd'
export const DATE_FORMAT_YEAR_MONTH = 'yyyy-MM'
export const DATE_FORMAT_YEAR = 'yyyy'
export const DATE_FORMAT_MONTH = 'MM'
export const DATE_FORMAT_DAY = 'dd'
